add HelloWorld.jar to assist with NoClassDefFoundError example complete NoClassDefFoundError example track changes to classpath file regarding HelloWorld.jar add comment to turn on assertions for Assert example code